image: docker:latest
services:
  - docker:dind

stages:
  - test

execute_tests:
  stage: test
  image: jotolo/ruby-postgresql-redis-elasticsearch
  script:
    - /etc/init.d/postgresql start
    - sudo service redis-server start
    - sudo service elasticsearch start
    - sudo -u postgres sh -c 'createuser root & createdb arachne_test'
    - bundle install
    - rake db:migrate RAILS_ENV=test
    - rake elasticsearch:reindex RAILS_ENV=test
    - rspec
  only:
    - develop
    - master

